apiVersion: 0.2.0
environments:
  dev:
    destination:
      namespace: davnn
      server: https://192.168.39.185:8443
    k8sVersion: v1.10.0
    path: dev
  prod:
    destination:
      namespace: davnn
      server: https://35.229.97.101
    k8sVersion: v1.10.7
    path: prod
kind: ksonnet.io/app
name: zookeeper
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
