apiVersion: 0.2.0
environments:
  local:
    destination:
      namespace: davnn
      server: https://192.168.39.126:8443
    k8sVersion: v1.10.0
    path: local
  gcp:
    destination:
      namespace: davnn
      server: https://192.168.39.126:8443
    k8sVersion: v1.10.0
    path: gcp
kind: ksonnet.io/app
name: davnn
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
